# Generated by Django 4.2 on 2026-02-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Pname', models.CharField(max_length=21)),
                ('Price', models.FloatField()),
                ('Company', models.CharField(max_length=21)),
                ('M_date', models.DateField()),
                ('Exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField()),
                ('Cname', models.CharField(max_length=21)),
                ('Address', models.CharField(max_length=21)),
                ('City', models.CharField(max_length=21)),
                ('products', models.ManyToManyField(to='application1.product')),
            ],
        ),
    ]
