# Generated by Django 6.0.2 on 2026-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Pname', models.CharField(max_length=21)),
                ('Price', models.FloatField()),
                ('Company', models.CharField(max_length=21)),
                ('M_date', models.DateField()),
                ('Exp_date', models.DateField()),
            ],
        ),
    ]
