# Generated by Django 4.2 on 2026-02-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=21)),
                ('Last_name', models.CharField(max_length=21)),
                ('Username', models.CharField(max_length=21)),
                ('P1', models.CharField(max_length=21)),
                ('P2', models.CharField(max_length=21)),
                ('Mobile_number', models.CharField(max_length=15)),
                ('Email_Address', models.CharField(max_length=17)),
            ],
        ),
    ]
