# Generated by Django 4.2 on 2026-02-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=21)),
                ('Esal', models.FloatField()),
                ('Design', models.CharField(max_length=21)),
                ('Company', models.CharField(max_length=21)),
                ('Email', models.EmailField(max_length=254)),
                ('J_date', models.DateField()),
            ],
        ),
    ]
