# Generated by Django 4.2 on 2026-02-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employess',
            new_name='Employees',
        ),
    ]
