# Generated by Django 4.2 on 2026-02-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('UserName', models.CharField(max_length=25)),
                ('P1', models.CharField(max_length=15)),
                ('P2', models.CharField(max_length=15)),
                ('Email_Address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=100)),
                ('public_date', models.DateField()),
                ('reporters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.reporters')),
            ],
        ),
    ]
